Repository python/typeshed, pull requests merged in 2020-05, with the labels that each got.

#4132 Add review guidelines
  CONTRIBUTING.md
Labels: project

#3371 More precise return types for open(), Path.open(), bz2.open(), etc.
  stdlib/2/__builtin__.pyi
  stdlib/2/io.pyi
  stdlib/2and3/builtins.pyi
  stdlib/2and3/bz2.pyi
  stdlib/3/gzip.pyi
  stdlib/3/io.pyi
  stdlib/3/lzma.pyi
  stdlib/3/pathlib.pyi
  third_party/2/pathlib2.pyi
Labels: topic-io

#4119 remove type ignores about python/mypy#5027
  stdlib/2and3/bz2.pyi
  stdlib/3/lzma.pyi
Labels: deferred

#4082 Make BytesIO inherit from BufferedIOBase.
  stdlib/3/gzip.pyi
  stdlib/3/io.pyi
  stdlib/3/lzma.pyi
  tests/stubtest_whitelists/py35.txt
  tests/stubtest_whitelists/py36.txt
  tests/stubtest_whitelists/py3_common.txt
Labels: topic-io

#4145 make io classes inherit from typing IO classes
  stdlib/3/io.pyi
Labels: topic-io

#4146 open: introduce concrete return types
  stdlib/2/__builtin__.pyi
  stdlib/2/io.pyi
  stdlib/2and3/builtins.pyi
  stdlib/3/io.pyi
Labels: topic-io
