Repository python/typeshed, pull requests merged in 2024-08, with the labels that each got.

#12337 Update `dircmp` for 3.13
  stdlib/@tests/stubtest_allowlists/py313.txt
  stdlib/filecmp.pyi
Labels: status: deferred

#12540 Update outdated labels and stub_uploader timing in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: project: policy

#12539 [February 2025] flake8-2020 is an archived repo
  stubs/flake8-2020/METADATA.toml
Labels: stubs: removal

#12537 Forbid extremely long line lengths in non-autogenerated stubs
  pyproject.toml
  stdlib/builtins.pyi
  stdlib/collections/__init__.pyi
  stdlib/email/message.pyi
  stdlib/ftplib.pyi
  stdlib/os/__init__.pyi
  stdlib/poplib.pyi
  stdlib/tkinter/ttk.pyi
  stubs/openpyxl/openpyxl/cell/__init__.pyi
  stubs/openpyxl/openpyxl/chart/series.pyi
  stubs/openpyxl/openpyxl/worksheet/_reader.pyi
  stubs/passlib/passlib/utils/handlers.pyi
  stubs/psycopg2/psycopg2/_psycopg.pyi
  stubs/redis/redis/client.pyi
  stubs/reportlab/reportlab/platypus/doctemplate.pyi
Labels: project: infrastructure

#12570 Remove seemingly redundant overloads from `IO`
  stdlib/typing.pyi
Labels: topic: io

#12568 socketserver: Use BufferedIOBase instead of BinaryIO
  stdlib/socketserver.pyi
Labels: topic: io

#12407 Add `unittest.runner._WritelnDecorator`
  stdlib/unittest/runner.pyi
Labels: topic: io

#12572 pyserial: Replace IO classes with protocols
  stubs/pyserial/serial/tools/miniterm.pyi
Labels: topic: io
