Repository python/typeshed, pull requests merged in 2024-09, with the labels that each got.

#12557 Enable more Ruff PYI rules with autofixes
  pyproject.toml
  stdlib/builtins.pyi
Labels: project: infrastructure

#12571 Move `BufferedIOBase.raw` to sub-classes
  stdlib/io.pyi
Labels: topic: io

#12527 Rewrote protobuf generation scripts in Python
  requirements-tests.txt
  scripts/generate_proto_stubs.sh
  scripts/sync_protobuf/_utils.py
  scripts/sync_protobuf/google_protobuf.py
  scripts/sync_protobuf/s2clientprotocol.py
  scripts/sync_protobuf/tensorflow.py
  scripts/sync_s2clientprotocol_protobuf_stubs.sh
  scripts/sync_tensorflow_protobuf_stubs.sh
  stubs/protobuf/METADATA.toml
  stubs/s2clientprotocol/METADATA.toml
  stubs/tensorflow/METADATA.toml
Labels: project: infrastructure, status: needs decision
